### ISSUE TITLE
roscpp scripts with node handle

### ISSUE THREAD

**Issue by a-z-e-r-i-l-a** [longjie/ros_cython_example#2]
Hi, 

You have a very nice example for using cython and catkin. I wanted to ask if it is also usable for interfacing a c++ script in ros that has nodehandle. I have made a ros_control hardware interface and want to now interface it with a python simulator. My choices seems to be Cython, boost/python, swig, cffi and etc.
[Here](http://wiki.ros.org/ROS/Tutorials/Using%20a%20C%2B%2B%20class%20in%20Python) I noticed a possible solution with boost/python and they mention something specific about having nodehandle and my other question was if you may think there might be an advantage in using cython compared to boost/python.

Thanks.

**Comment by longjie** [comment]
Sorry I don't have experience of boost/python. Generally speaking, we should consider to use ROS's Message/Action/Service to communicate with other processes.
