### ISSUE TITLE
dynamic module does not define module export function (PyInit_...) 

### ISSUE THREAD

**Issue by a-z-e-r-i-l-a** [longjie/ros_cython_example#3]
Hi, 

I wanted to ask if you know a way to have the generated python wrapper **python3 compatible**.  I had a try similar to ros_cython_example but the generated python wrapper was only usable by python2. For python3 it gives the error:

`dynamic module does not define module export function (PyInit_..)`

I tried some of the suggestions over internet about this, but it seems ros or cmake adds some more complexity to the issue, but there should be a solution for it.

Thank you.

**Comment by longjie** [comment]
Sorry I have no idea. I have not tried with python3. I'm afraid we cannot build package with python3 with ROS except the latest version Noetic.

**Comment by a-z-e-r-i-l-a** [comment]
yea but for a python wrapper of a c++ code it shouldn't matter if it's python 3 right? many python codes with melodic also are in general usable in python 3.

I think the source of this issue is from the cmake files. cython by its ow can make python3 compatible wrappers.

there's this package called scikit-build has a more updated version of these cmake files, but I'm not sure how to use it through catkin_python_setup() or directly. 

the source of this issue is for sure the original cmake files for cython. I'd be very glad if you noticed a workaround for it.....

**Comment by longjie** [comment]
I can't get exactly what you mean, but I can successfully run my ros_cython_example with python3, on ROS melodic. Check out python3 branch (https://github.com/longjie/ros_cython_example/tree/python3)

make sure you will build it with python3 as:

```
catkin config -DPYTHON_EXECUTABLE=~/pytorch/bin/python -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so
```
and to do `pip install` required pyhon modules (i.e. ros, rospkg, catkin_pkg and empy).

**Comment by a-z-e-r-i-l-a** [comment]
so I have used the catkin config you mentioned(-DPYTHON_EXECUTABLE..) which works in my work space now but the moment I add name of another package from my workspace in find_package(), although it compiles I get this import error:I
`mportError: ....: undefined symbol: _Py_ZeroStruct`
. It's quite strange how this effects catkin_python_setup...

I also couldn't use '-DPYTHON_INCLUDE_DIR=/usr/include/python3.6m' because o
